patch:
  schema_list:
    - schema: double_pinyin_flypy
    - schema: luna_pinyin_simp
  switches:
    - name: ascii_mode
      reset: 1
  ascii_composer/good_old_caps_lock: true
  ascii_composer/switch_key:
    Caps_Lock: clear
    Shift_L: commit_code
    Shift_R: inline_ascii
    Control_L: noop
    Control_R: noop
